version: '3'
services:
  thisismoney-app:
    build: .
    container_name: thisismoney-app
    ports:
      - "8080:8080"
    env_file:
      - .env

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - thisismoney-app