# docker-compose.yml
services:
  thisismoney-app:
    platform: linux/amd64
    image: jaeyoungjoo/thisismoney-app:latest
    container_name: thisismoney-app
    expose:
      - "8080"
    restart: unless-stopped
#    env_file: .env # 서버에 따로 .env파일 없으면 제거.
    volumes:
      - ./app/config/google_credentials.json:/app/config/google_credentials.json
    networks:
      - app-network

  nginx:
    platform: linux/amd64
    image: jaeyoungjoo/thisismoney-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot # 챌린지가 저장될 디렉토리
    depends_on:
      - thisismoney-app
    restart: unless-stopped
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
